baseURL = '/'
title = 'Mateus'
enableRobotsTXT = true


# language
defaultContentLanguage = 'pt'
[languages]
	[languages.en]
		title = "Mateus' Site"
		weight = 2
	[languages.pt]
		title = "Site de Mateus"
		weight = 1
			
# menu
	# pt
	[[languages.pt.menu.main]]
		name = "Home"
		url = '/'
		weight = 1
	[[languages.pt.menu.main]]
		name = "Animações"
		url = '/animations'
		img = 'animations'
		weight = 2
	[[languages.pt.menu.main]]
		name = 'Jogos'
		url = '/games'
		img = ''
		weight = 3
	#[[languages.pt.menu.main]]
	#	name = 'Música'
	#	url = '/music'
	#	img = ''
	#	weight = 4
	[[languages.pt.menu.main]]
		name = 'Blog'
		url = '/blog'
		img = ''
		weight = '10'
	[[languages.pt.menu.main]]
		name = 'Sobre'
		url = '/about'
		img = ''
		weight = 999
	# en
	[[languages.en.menu.main]]
		name = 'Home'
		url = '/'
		img = ''
		weight = 1
	[[languages.en.menu.main]]
		name = 'Animations'
		url = 'animations'
		img = ''
		weight = 2
	[[languages.en.menu.main]]
		name = 'Games'
		url = '/games'
		img = ''
		weight = 3
	#[[languages.en.menu.main]]
	#	name = 'Music'
	#	url = '/music'
	#	img = ''
	#	weight = 4
	[[languages.en.menu.main]]
		name = 'Blog'
		url = '/blog'
		img = ''
		weight = '10'
	[[languages.en.menu.main]]
		name = 'About'
		url = '/about'
		img = ''
		weight = 999

# sectionPagesMenu = "main"


# taxonomies
[taxonomies]
	tag = "tags"
	category = "categories"
	software = "softwares"
	
